# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poll',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='poll',
            new_name='topic',
        ),
    ]
