# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20170823_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='name',
            new_name='entry_text',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='topic_text',
        ),
        migrations.AddField(
            model_name='entry',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
