# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20170823_1711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='entry_text',
            new_name='choice_text',
        ),
    ]
